name: Deploy Development Environment

env: 
    environmentName = 'qa'

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep
      uses: azure/arm-deploy@v2
      with:
        region: ${{ vars.REGION }}
        scope: 'subscription'
        template: ./bicep/main.bicep
        parameters: projectName=${{ vars.PROJECT_NAME }} environmentName=${{ var.environmentName }} region=${{ vars.REGION }}
        failOnStdErr: false
    