name: Deploy QA Environment

env: 
    environmentName: 'qa'

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep
      uses: azure/arm-deploy@v2
      with:
        region: ${{ vars.REGION }}
        scope: 'subscription'
        template: ./bicep/main.bicep
        parameters: projectName=${{ vars.PROJECT_NAME }} environmentName=${{ env.environmentName }} region=${{ vars.REGION }} AzureBlob_ConnectionString=${{ secrets.AZUREBLOB_CONNECTIONSTRING }} cognitiveservicescomputervision_ConnectionKey=${{ secrets.COGNITIVESERVICESCOMPUTERVISION_CONNECTIONKEY }} AzureBlob_V2_ConnectionKey=${{ secrets.AZUREBLOB_V2_CONNECTIONKEY }} 
        failOnStdErr: false
      