name: Deploy Dev Environment

on:
   workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
          
        - name: Trigger Deploy Environment
          uses: ./deployEnvironment.yml
          with:
            environmentName: 'dev'