name: Deploy Environment

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'Environment Name'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep
      uses: azure/arm-deploy@v2
      with:
        region: ${{ vars.REGION }}
        scope: 'subscription'
        template: ./bicep/main.bicep
        parameters: projectName=${{ vars.PROJECT_NAME }} environmentName=${{ inputs.environmentName }} region=${{ vars.REGION }}
        failOnStdErr: false
    