name: Deploy Dev Environment

on:
   workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Environment
        uses: ./.github/workflows/deployEnvironment.yml
        with:
            environmentName: 'dev'